#!/bin/bash
clear
check=0
check=1
ok="ok"
ENTER="press ENTER for main menu"
#colors
w='\e[97m'
g='\033[1;92m'
r='\033[1;91m'
a='\033[1;94m'
b='\e[1;4m'
cyan='\033[1;36m'
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
reset='\033[0m'
G='\e[110m'
G1='\e[101m'
o='\033[0m'
#banner
sleep 0.5
echo -e $yellow$blue$red
figlet -f big "DxTmaster"

echo -e "                   $g"Master"$r"Script"$w"Dxt"" 
echo -e "$a              # # # # # # # # # # # #"
echo -e "$a              #$G                     $o$a#"
echo -e "$a              #$G    $r"DxTmaster  V3.2"$a   $o$a#"
echo -e "$a              #$G                     $o$a#"
echo -e "$a              # # # # # # # # # # # #"
echo
echo -e "  $G1$w Selamat Datang di Alat Ini Untuk Pengujian Penetrasi $o" 
echo -e $o"$blue               Made by$yellow Dextrobet "$o
echo -e " $g          Developers :  Stranger "
echo " "
echo -e "              $red Press $green ENTER to Continue"
echo -e $yellow
echo -n -e "Root@DxT~$ "
sleep 2
read tmp
echo -e " "
echo -e "$blue THE MAIN MENU"
sleep 0.5
echo -e "$red --------------"
sleep 0.1
echo -e "$a      [$r"01"$a"]"$g PAYLOAD GENERATOR"
sleep 0.1
echo -e "$a      [$r"02"$a"]"$g ADVANCE NMAP SCAN"
sleep 0.1
echo -e "$a      [$r"03"$a"]"$g WEB-HACKS"
sleep 0.1
echo -e "$a      [$r"04"$a"]"$g PASSWORD CRACK"
sleep 0.1
echo -e "$a      [$r"05"$a"]"$g Termux Tools"
sleep 0.1
echo -e "$a      [$r"06"$a"]"$g MY SERVER"
sleep 0.1
echo -e "$a      [$r"07"$a"]"$g ABOUT"
sleep 0.1
echo -e "$a      [$r"08"$a"]"$g UPDATE ME"
sleep 0.1
echo -e "$a      [$r"09"$a"]"$g CONTACT ME"
sleep 0.1
echo -e "$a      [$w"XX"$a"]"$g EXIT $reset"
sleep 0.5
echo -e $yellow
echo -n $B "Root@DxT~$ "
read option
if [[ $option == "" ]];
then
	echo -e "$red Please enter correct number of choice"
	echo
	echo -e "$green Plz wait... You are redirecting to main menu"
	sleep 2
DxTmaster
fi

create_payload()
{
python2 $PREFIX/share/DxTmaster/.modules/.pay.py
DxTmaster
}

about()
{
echo -e "$green                    DxTmaster $yellow
This tool is to provide easy user interface 
My aim behind this tool is to make penetration testing easy 
like payload creation, metasploit installation, 
ngrok installation, network scanning and Websites Hacking 
& Wait for my updates of$r DxTmaster$yellow tool 
with some extra features and options and all 
$red (o_O)$reset
echo
echo -e "$red                    press ENTER"
echo -n "Root@DxT~$ "
read tmpp
DxTmaster
}

update()
{
echo -e "\033[1;33m Updating ..."
echo
cd $PREFIX/share/DxTmaster/
git reset --hard > /dev/null
git pull
chmod +x *
cp -f $PREFIX/share/DxTmaster/DxTmaster $PREFIX/bin/
echo
echo
echo -e "\033[1;31m Updated Successfully \033[0m"
echo
echo -e "$red                    press ENTER"
echo -n "Root@DxT~$ "
read tmp
DxTmaster
}

password()
{
clear
$PREFIX/share/DxTmaster/.modules/.password
echo -e "$red                    press ENTER"
echo -n "Root@DxT~$ "
read tmp
DxTmaster
}

termux()
{
clear
$PREFIX/share/DxTmaster/.modules/.Termux_Tools
DxTmaster
}


contact()
{
echo -e "$green ********** Do You Want to Contact Me ? **********"
echo -e "$r                     press ENTER$reset"
echo -n "[DxTmaster]~#:"
read tmp4
echo -e "$w My Facebook ID> $yellow www.facebook.com/robet master Dxt"
echo -e "$red               $ENTER$reset"
echo -n "[DxTmaster]~#:"
read tmp5
DxTmaster
}

nmap()
{
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; 
then
clear
echo -e $g "welcom to DxTmaster_ScaN"
echo -e "$yellow"[✔]:[ "$w"Internet"$yellow ]:$green connected !"
sleep 3
clear
echo "DxTmaster_ScaN "
sleep 0.3
clear
echo "DxTmaster_ScaN ./ "
sleep 0.3
clear
echo "DxTmaster_ScaN ..\ "
sleep 0.3
clear
echo "DxTmaster_ScaN .../ "
sleep 0.3
clear
echo "DxTmaster_ScaN ....\ "
sleep 0.3
clear
echo "DxTmaster_ScaN ...../ "
sleep 0.3
clear
echo "DxTmaster_ScaN ......\ "
sleep 0.3
clear
echo "DxTmaster_ScaN ......./ "
sleep 0.3
clear
echo "DxTmaster_ScaN ........\ "
sleep 0.3
clear
echo "DxTmaster_ScaN ........./ "
sleep 0.3
clear
echo "DxTmaster_ScaN ...........\ "
$PREFIX/share/DxTmaster/.modules/.DxTmaster_ScaN
else
echo -e "$red sorry ther is no internet im your mobile "
echo -e "$red you can't use DxTmaster_ScaN"
echo -e "$yellow "["$red "x"$yellow ]:[$w "Internet"$yellow ]:$red Not connected !"
sleep 20
$PREFIX/share/DxTmaster/DxTmaster
fi

}

web_hacking()
{
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; 
then
clear
echo -e $g "welcom to web_hacking"
echo -e "$yellow"[✔]:[ "$w"Internet"$yellow ]:$green connected !"
sleep 4 
clear
echo "WEB-HACK "
sleep 0.2
clear
echo "WEB-HACK ./ "
sleep 0.2
clear
echo "WEB-HACK ..\ "
sleep 0.2
clear
echo "WEB-HACK .../ "
sleep 0.2
clear
echo "WEB-HACK ....\ "
sleep 0.2
clear
echo "WEB-HACK ...../ "
sleep 0.2
clear
echo "WEB-HACK ......\ "
sleep 0.2
clear
echo "WEB-HACK ......./ "
sleep 0.2
clear
echo "WEB-HACK ........\ "
sleep 0.2
clear
echo "WEB-HACK ........./ "
sleep 0.2
clear
echo "WEB-HACK ...........\ "
$PREFIX/share/DxTmaster/.modules/.web
else
echo -e "$red sorry ther is no internet im your mobile "
echo -e "$red you can't use WEB-HACK"
echo -e "$yellow "["$red "x"$yellow ]:[$w "Internet"$yellow ]:$red Not connected !"
sleep 20
$PREFIX/share/DxTmaster/DxTmaster
fi

}

server()
{
$PREFIX/share/DxTmaster/.modules/.server

}


case "$option" in
	1) if [ $check = 0 ];
		then
			create_payload
			fi
			create_payload
		 ;;
	2) nmap
		;;
	3) web_hacking
		;;
	4) password
		;;
	5) termux
		;;
	6)  server
		;;
	7)  about
		 ;;
	8)  update
		 ;;
	9) contact
		;;
esac

if [ $master -eq x ] || [ $master -eq X ] || [ $master -eq XX ] || [ $master -eq xx ] ;
then
clear
echo " by by "
exit 
else
clear
echo "E.................................\ "
sleep 0.1
clear
echo "EX................................/ "
sleep 0.1
clear
echo "EXI...............................\ "
sleep 0.1
clear
echo "EXIT............................../ "
sleep 0.1
clear
echo "EXIT D............................\ "
sleep 0.1
clear
echo "EXIT Dx.........................../ "
sleep 0.1
clear
echo "EXIT DxT..........................\ "
sleep 0.1
clear
echo "EXIT DxT........................./ "
sleep 0.1
clear
echo "EXIT DxT H.......................\ "
sleep 0.1
clear
echo "EXIT DxT HA....................../ "
sleep 0.1
clear
echo "EXIT DxT HAC.....................\ "
sleep 0.1
clear
echo "EXIT DxT HACK..................../ "
sleep 0.1
clear
echo "EXIT DxT HACK T..................\ "
sleep 0.1
clear
echo "EXIT DxT HACK TO................./ "
sleep 0.1
clear
echo "EXIT DxT HACK TOO................\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL.............../ "
sleep 0.1
clear
echo "EXIT DxT HACK TOOL...............\ "
sleep 0.1
clear
echo -e "\033[1;91robet master  wish you all the best ♡ you all "
sleep 3
clear 
exit
fi
read robet